### ISSUE TITLE
Service Circle Pages

### ISSUE THREAD

**Issue by Janis1992-08** [Janis1992-08/Capstone-Project-ServiceCircle#1]
Acceptance Criteria

- [ ] Create a header "Service Circle" and
      intro text like displayed in the wireframe.

- [ ] On Service Category Page the User can navigate to Subcategories.

- [ ] On Subcategories Page the User can choose between the offered Services 
       and navigate to them.
- [ ] Error Handling: 404 Page not found! and  500 Internal Server Error "Services temporarily not available".

**Comment by mbosselmann** [comment]
Hi Team Service Circle,
I have some remarks for you regarding your user story:

**In general:**
- please stay with the our structure that you can find in the handout for the user stories workshop and also in the web capstone docs:

```md
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team
```

- In this user story you want to implement two features: first the list of service and second a search functionality. These should be separated into two user stories to have manageable small user stories.
- But I think it can be a good idea to have the `Service Provider List` as first user story and the search functionality as second user story.

**Title**
- I am not sure if the title is really specific about the feature you are implementing. Something like "Service Provider List" might be better.

**Value Proposition**
- Currently there is not value proposition. Please add you value proposition to describe the benefit of the feature from a user's perspective.

**Description:**
- When you split this user story in two user stories you should also remove for your first user story the searchbar.

**Acceptance Criteria:**
- Most of your acceptance criteria are developer tasks (create searchbar, create service cards etc.)
- Your acceptance criteria should describe what from the users perspective is necessary to see the user story as completed.
- Questions you should ask for your acceptance criteria are for example:
  - What will be displayed for the user?
  - Are there user interactions the user does have with the feature?
  - Does the feature has different states that needs to be considered?
  - Are there errors that might occur?
- For this critierion: "Error Handling: 404 Page not found! and 500 Internal Server Error "Services temporarily not available": As you will start to work with a example data that is part of your app (and you do not need to fetch) these kind of errors won't come.

**Tasks:**
- part of your tasks should also be that you need to create example data for your service list.

I hope this does help! Feel free to ask me if you have further questions. :)
