### ISSUE TITLE
Update and Delete Service Cards

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#13]
## Value proposition
As a User
I want to to edit and delete service cards
In order to i can update and delete service cards if the card needs changes or i will not offer a service anymore

## Acceptance criteria

**Edit:**
- [ ] User can select an existing Service Card and edit the information
- [ ] Changes persist in MongoDB after saving
- [ ] Input validation occurs before saving to the database

**Delete:**
- [ ] User can select an existing Service Card and permanentely delete it
- [ ] The deleted Service Card is permanentl removed from the MongoDB

## Tasks

- [ ] **Frontend:** add Edit Button to Service Cards. Implement the editing function 
to modify existing data in the Service Card. Add a delete Button for removing the Service Cards.

- [ ] **Backend:** Create API endpoints for editing and deleting Service Cards. 
Implement input validation before saving to the database. Create functionality with MongoDB to save changes and 
delete a whole Service Card

**Comment by JulianKle** [comment]
I'm a bit confused, when did you add the database functionality? Otherwise, it would have to be added in the front end that a DELETE request is started. You would also have to make sure that you pass the id of the object to be deleted (ServiceCard) to the request or method.

**Comment by Alexander-Kolotow** [comment]
i answered in slack, thanks!

**Comment by mbosselmann** [comment]
Hi Team ServiceCircle,
I think you just changed the user story again after I read the old version. 😅 
Just one remark for your acceptance criteria: 
- `User can select an existing Service Provider and permanentely delete it from the database`

This is somehow a mix between the user perspective and an implementation detail that is not relevant for the user. You could be more descriptive here and explain the user flow by answering the following questions:
  - How can the user delete a service provider?
  - What happens after deleting a service provider?

I hope this does help. :)

**Comment by Alexander-Kolotow** [comment]
Hello Mareike, thank you for your input. I have taken your feedback into account and made some improvements to the sentence to align more with the acceptance criteria..hope now it is fine?

**Comment by mbosselmann** [comment]
Hi Alexander,
just one last thing for the last sentence of the acceptance criterion. I would remove the part with the database (implementation detail that is not interesting for the user) and write: "After deleting the card it will not be shown in the UI anymore." If you do this last change then its fine! 👍 
So I approve this user story now as I trust you in changing this too. ✅

**Comment by Alexander-Kolotow** [comment]
thanks, did it!
