### ISSUE TITLE
Update Service Cards

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#14]
## Value proposition

As a <user/role>
I want to edit service cards
In order to i can update service cards if the card needs changes 

## Acceptance criteria

**Edit:**

    -[ ] User can select an existing Service Card and edit the information
       -[ ]  Changes persist in MongoDB after saving
       -[ ]  Input validation occurs before saving to the database

## Tasks

- [ ] Create Branch updateServiceCards
- [ ] **Frontend:** Add Edit Button to Service Cards. Implement the editing function
to modify existing data in the Service Card.
- [ ] **Backend:** Create API endpoints for editing Service Cards.
Implement input validation before saving to the database. Create functionality with MongoDB to save changes

**Comment by ThomasKirst** [comment]
The story looks good so far. However, I would add the wireframe of the edit form with the pre-filled data from the ServiceCard. You should be able to reuse one of your former layouts for this and slightly adjust it – with an "Update" button instead of "Create" or something similar.
Then it would also be clear where the form appears. Not that there are misunderstandings and one wonders, is the Service Card now edited directly on the spot or does the user come to an extra page where the form is edited.

Something minor: we usually name branches like `update-service-cards` instead of camelCase.

Great you´re mentioning _input validation_ which is an important task here 👍

**Comment by ThomasKirst** [comment]
All good! I would name the branch something like `feature/edit-service-card` or similar, though. It would be great to get a visual idea of how the card would look like in the edit mode, but it´s not a must.
