### ISSUE TITLE
Service Card Form

### ISSUE THREAD

**Issue by Janis1992-08** [Janis1992-08/Capstone-Project-ServiceCircle#2]
### Value proposition
As a User
I want to to fill out a form to create a Service Card
so that i can offer my services to other users

### Description

![Image](https://github.com/Janis1992-08/Capstone-Project-ServiceCircle/assets/139806458/0d76a854-a30c-4ef3-a52a-b0933be5ae00)

### Acceptance Criteria
- [ ] The user sees an offer button on the homepage

- [ ] The user can click on the "Offer" button 
and will be redirected to the Service Card Form page

- [ ]  on the service card form page, the user sees input fields where you can enter your name, service category, skills and needs.

- [ ] By clicking on the Create button, the input fields are cleared and a notification is displayed that the service has been successfully created
- [ ] The service card will then appear further down in the app under the form

### Task

- [ ] Creating Branch "service card form"
- [ ] Creating a button with a Link that brings the user to the service card form page
- [ ] Creating a component CreateServiceCardForm
- [ ] Implement the required input fields 
for first name, last name, skills, needs, email and phone
- [ ] Integrate dropdown menu for category and subcategory
- [ ] all fields are required! 
- [ ] Implement functions for handling 
form changes (handleChange) 
and submitting the form (handleSubmit)

**Comment by Janis1992-08** [comment]
### Value proposition
As a User
I want to 
so that


### Description


![Image](https://github.com/Janis1992-08/Capstone-Project-ServiceCircle/assets/139806458/dae96d44-3702-452b-9529-d3145532d251)





### Acceptance Criteria






### Task
