### ISSUE TITLE
DB - for Edit Logic

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#21]
## Value proposition
As a User
I want to persist the changes i have made in a service card
In order to save the changes not only in the frontend for one device, but for any device by fetching the data from a database

## Description

We now want to switch from local storage in the frontend to the database so that changes are visible to everyone on every device and browser.

## Acceptance criteria

- [ ] The made changes on a service card should persist in the database

## Tasks

- [ ] Create branch database-edit-service-card
- [ ] Define a database schema that fits our structure
- [ ] Create API endpoint for the update operation related to service cards
- [ ] Implement the API route to handle data retrieval for update
- [ ] Send requests to the API endpoint and remove local storage
- [ ] Add HTTP requests, in this case GET, POST and PUT, to communicate with the backend

**Comment by mbosselmann** [comment]
Hi Team ServiceCircle,
LGTM! 🦊 Just one **note:** For the update operation only `PUT` is needed:
`Add HTTP request (PUT) to communicate with the backend` :)

**Comment by Alexander-Kolotow** [comment]
thanks mareike, i will update that in the US.
