### ISSUE TITLE
Create persistent Service Provider Cards

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#25]
## Value proposition
As a User
I want to create Service Provider Cards which persist
In order to display the cards i have created to anyone who may be concerned

## Description

The user should be able to create service provider cards that persist on the UI and can be retrieved by anyone interested in viewing these cards.

## Acceptance criteria
- [ ] Users can create service provider cards through the provided form
- [ ] Upon submission the data is persisted
- [ ] The UI displays the created service provider cards

## Tasks
- [ ] Create branch create-service-cards
- [ ] Define a POST API route for creating service provider cards and call the .create method
- [ ] Tell the form submit handler to use the POST API route:
- [ ] If the backend response is successful following the POST fetch, 
we can useSWR to revalidate the data by invoking the mutate function.

**Comment by mbosselmann** [comment]
Hi Team ServiceCircle,
good start to the new year! 💪 Here are my remarks:

**Value Proposition:**
I think that your value proposition does not reflect the need to implement a database, as the local storage also persists the data. A more specific advantage would be that the data stored in a database is available on different devices and can no longer be viewed in just one browser.

**Description:**
The description just repeats the value proposition. I think you can mention here that there will be no visual difference to before for the user and refer to the PR where you build the create functionality. (#2 ) :)

Feel free to ask if you have further questions! :)

**Comment by Alexander-Kolotow** [comment]
> Hi Team ServiceCircle, good start to the new year! 💪 Here are my remarks:
> 
> **Value Proposition:** I think that your value proposition does not reflect the need to implement a database, as the local storage also persists the data. A more specific advantage would be that the data stored in a database is available on different devices and can no longer be viewed in just one browser.
> 
> **Description:** The description just repeats the value proposition. I think you can mention here that there will be no visual difference to before for the user and refer to the PR where you build the create functionality. (#2 ) :)
> 
> Feel free to ask if you have further questions! :)

Hello Mareike, thanks for your review. I made an edit. Hope it is more accurate now. :)

**Comment by mbosselmann** [comment]
LGTM! 🦊
