### ISSUE TITLE
DB - Read

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#26]
## Value proposition
As a User
I want to save and read my Service Provider Cards across any device.
In order to have a persistent and personalized UX.

## Description
By connecting to a database, users can retrieve and read their own and third-party service cards from all devices at any time.

## Acceptance criteria
- [ ] The created Service Provider Cards are stored persistently for the User and accessible from any device.

## Tasks
- [ ] Create branch db-read-service-cards
- [ ] Create a database to which all team members have access
- [ ] Create the connection to the database
- [ ] Create a database schema that aligns with the structure of the array of objects
- [ ] Create a read function (GET-method!)
- [ ] Use SWR to fetch the data from the database

**Comment by mbosselmann** [comment]
Hi Team ServiceCircle,
another good start! 💪 Here are my remarks:

**Value Proposition:**
- I think the value of implementing the read functionality is not to save service cards. It is only the possibility to read service cards from any device.  My suggestion:

As a user,
I want to view my services on various devices,
to ensure easy, persistent and convenient access to my service offers. 

**Description:**
Even though the service list wont' change, some things differ from before and should be shown with wireframes: 
1. There will be a loading state of the data. As the fetching of the data will need some time you should add what will happen while fetching. :)
2. There should also be a error text displayed that explains to the user what happened when it was not possible to load the data. [See for example the first example user story of the movie app in our capstone docs.](https://web-capstone-docs.neuefische.de/guides/user-stories#1-movies-list)

**Acceptance criteria/Tasks**
- These should be updated too according to the suggested changed to the description. :)

I hope this does help. :)

**Comment by Alexander-Kolotow** [comment]
> Hi Team ServiceCircle, another good start! 💪 Here are my remarks:
> 
> **Value Proposition:**
> 
>     * I think the value of implementing the read functionality is not to save service cards. It is only the possibility to read service cards from any device.  My suggestion:
> 
> 
> As a user, I want to view my services on various devices, to ensure easy, persistent and convenient access to my service offers.
> 
> **Description:** Even though the service list wont' change, some things differ from before and should be shown with wireframes:
> 
>     1. There will be a loading state of the data. As the fetching of the data will need some time you should add what will happen while fetching. :)
> 
>     2. There should also be a error text displayed that explains to the user what happened when it was not possible to load the data. [See for example the first example user story of the movie app in our capstone docs.](https://web-capstone-docs.neuefische.de/guides/user-stories#1-movies-list)
> 
> 
> **Acceptance criteria/Tasks**
> 
>     * These should be updated too according to the suggested changed to the description. :)
> 
> 
> I hope this does help. :)

thank you! 👍🏻 . Edited. :)
