### ISSUE TITLE
Service Categorie Pages

### ISSUE THREAD

**Issue by Janis1992-08** [Janis1992-08/Capstone-Project-ServiceCircle#3]
Acceptance Criteria

- [ ] Create Service Categories and Subcategories of Services offered.

- [ ] On Service Category Page the User can navigate to Subcategories.

- [ ] On Subcategories Page the User can choose between the concrete, offered Services 
       and navigate to them.
- [ ] Error Handling: 404 Page not found! and  500 Internal Server Error "Services temporarily not available".

Task 

- [ ] Creating Branch "Service Categorie Pages"

- [ ] Service Category Page: create a <Header/> component and a <Button/> component 
for the different categories. Redirect to homepage with the <Link/> component.

- [ ] Subcategory Page: use the <Button/> component to create the Subcategories 
      .Redirect to Service Category Page with the <Link/> component.

- [ ] Service Provider Page: Use the <Header/> component and redirect to Subcategory Page 
        with the <Link/> component.

![Image](https://github.com/Janis1992-08/Capstone-Project-ServiceCircle/assets/139806458/48ff0029-8f01-42b7-95bd-c456d5072277)

**Comment by mbosselmann** [comment]
Hi Team Service Circle,
now also my remarks for your second user story:

**In general:**
- regarding the structure and the acceptance criteria please see what I wrote already as comment for your Service Provider List :)

**Tasks:**
- "Create a component **(for what?)** and a component for the different categories." - there is something missing I think
- As there will be no other homepage I think your `Service Category Page` will be your `pages/index.js` as this will be the first thing the user will see when the user uses your app or? 🤔 
- If you want to implement multiple routes with your category pages then a task might be to `implement dynamic routing` as this would be the way to go I suppose.
- It could be easier two split this user story in two user stories: first only implementing the main categories and later the sub categories as both together might be really complex, but I would leave this up to you to decide. Just a thought.

I hope this does help! Feel free to ask me if you have further questions! 💪

**Comment by Alexander-Kolotow** [comment]
Hi Mareike, i think we will not need the last part, because it is already a part of User Story 1? 

> _Service Provider Page:

Creating Service Cards for each provider with name, skills, and needs.
create the Toggle Button with the Contact informations for the Service Cards
Creating example data for the service list._

thanks for your review! 💪
