### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by Alexander-Kolotow** [Janis1992-08/Capstone-Project-ServiceCircle#46]
## Value proposition

As a User
I want to receive information about the developers and owners of this app
In order to understand why and by whom this app was developed and what the idea behind it is

## Description

As a User, I can get information about the app, the core idea and the developers in the footer area. I can also access their social media channels via linked icons.

## Acceptance criteria

- [ ] There is a footer
- [ ] There is an "about us" text in the footer
- [ ] There are 3 columns below the "about us" text with linked social media icons for Amjed, Janis and Alex

## Tasks

- [ ] Create the branch "aboutUs"
- [ ] Create a footer element on the index.js
- [ ] Create an appropriate Heading for "About us" (probably <h2>)
- [ ] Create Paragraphs for the text
- [ ] Create 3 separate columns. One column for Amjed, one for Janis and one for Alex. The existing social media channels are linked in the respective columns.
- [ ] Be creative when it comes to styling!

**Comment by JuliaSchw** [comment]
looks great :)
